name: Ready the code and deploy the app

on: [push, workflow_dispatch]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/Coping codes
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.11

      - name: check node version
        run: node -v

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

  build-code:
    runs-on: ubuntu-latest
    needs: test-code
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.11

      - name: Checkout/Coping codes
        uses: actions/checkout@v6

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the codes
        run: pnpm build

  deploy-code:
    runs-on: ubuntu-latest
    needs: build-code
    steps:
      - name: Deploy the codes
        run: echo "Deploying the app..."
